"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { saveSession } from "../../lib/session";

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:4000";
const MAX_CHARS = 4000;

const EXAMPLES = [
    {
        label: "🎮 GameFi NFT",
        text: "A blockchain-based mobile game where players collect, battle, and trade AI-generated character NFTs. Each character has unique stats generated by an AI based on market sentiment. Players earn tokens by winning battles.",
    },
    {
        label: "🏥 MedChain",
        text: "A decentralized medical records system on EVM that lets patients control who accesses their health data. Doctors request access via smart contract, patients approve with their wallet. Records are encrypted and stored on IPFS.",
    },
];

export default function SubmitPage() {
    const router = useRouter();
    const [caseText, setCaseText] = useState("");
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState("");
    const remaining = MAX_CHARS - caseText.length;

    async function handleSubmit(e) {
        e.preventDefault();
        if (!caseText.trim()) return;
        setLoading(true);
        setError("");

        try {
            const res = await fetch(`${BACKEND_URL}/evaluate`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ case_text: caseText.trim() }),
            });

            if (!res.ok) {
                const err = await res.json();
                throw new Error(err.error || `API error ${res.status}`);
            }

            const data = await res.json();
            saveSession({ caseText: caseText.trim(), evaluation: data });
            router.push("/deliberation");
        } catch (err) {
            setError(err.message);
            setLoading(false);
        }
    }

    return (
        <div className="page-wrapper">
            {/* Nav */}
            <nav className="nav container">
                <span className="nav-logo">⚖️ Agent Jury</span>
                <div className="nav-links">
                    <Link href="/submit" className="nav-link active"><span>Submit</span></Link>
                    <Link href="/history" className="nav-link"><span>History</span></Link>
                </div>
            </nav>

            <div className="container">
                {/* Hero */}
                <div style={{ textAlign: "center", marginBottom: "2.5rem" }} className="fade-in">
                    <div style={{
                        display: "inline-block",
                        padding: "0.35rem 1rem",
                        borderRadius: "100px",
                        background: "rgba(124, 58, 237, 0.15)",
                        border: "1px solid rgba(124,58,237,0.3)",
                        fontSize: "0.78rem",
                        fontWeight: 600,
                        color: "#a855f7",
                        marginBottom: "1.25rem",
                        letterSpacing: "0.05em",
                        textTransform: "uppercase"
                    }}>
                        🤖 3 AI Agents · On-Chain Verdicts · Monad EVM
                    </div>
                    <h1 style={{
                        fontSize: "clamp(2rem, 5vw, 3.2rem)",
                        fontWeight: 900,
                        lineHeight: 1.1,
                        marginBottom: "1rem",
                        background: "linear-gradient(135deg, #f1f5f9 0%, #94a3b8 100%)",
                        WebkitBackgroundClip: "text",
                        WebkitTextFillColor: "transparent",
                        backgroundClip: "text",
                    }}>
                        Submit Your Idea.<br />
                        <span style={{
                            background: "linear-gradient(135deg, #7c3aed, #06b6d4)",
                            WebkitBackgroundClip: "text",
                            WebkitTextFillColor: "transparent",
                            backgroundClip: "text",
                        }}>Let the Jury Decide.</span>
                    </h1>
                    <p style={{ color: "var(--text-secondary)", fontSize: "1.05rem", maxWidth: 540, margin: "0 auto" }}>
                        Three specialized AI agents evaluate your project idea on feasibility, innovation, and risk. The verdict is saved on-chain forever.
                    </p>
                </div>

                {/* How it works */}
                <div style={{
                    display: "grid",
                    gridTemplateColumns: "repeat(3, 1fr)",
                    gap: "0.75rem",
                    marginBottom: "2rem"
                }} className="fade-in fade-in-delay-1">
                    {[
                        { icon: "🔧", title: "Feasibility", desc: "Can it be built?" },
                        { icon: "💡", title: "Innovation", desc: "Is it original?" },
                        { icon: "🛡️", title: "Risk & Ethics", desc: "Is it safe?" },
                    ].map((a) => (
                        <div key={a.title} className="glass-card" style={{ padding: "1.1rem", textAlign: "center" }}>
                            <div style={{ fontSize: "1.5rem", marginBottom: "0.4rem" }}>{a.icon}</div>
                            <div style={{ fontWeight: 700, fontSize: "0.9rem" }}>{a.title}</div>
                            <div style={{ color: "var(--text-muted)", fontSize: "0.78rem" }}>{a.desc}</div>
                        </div>
                    ))}
                </div>

                {/* Form */}
                <div className="glass-card fade-in fade-in-delay-2" style={{ padding: "2rem" }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.75rem" }}>
                        <h2 style={{ fontSize: "1rem", fontWeight: 700 }}>Describe your project idea</h2>
                        <div style={{ display: "flex", gap: "0.5rem" }}>
                            {EXAMPLES.map((ex) => (
                                <button
                                    key={ex.label}
                                    onClick={() => setCaseText(ex.text)}
                                    className="btn btn-ghost"
                                    style={{ padding: "0.3rem 0.7rem", fontSize: "0.72rem" }}
                                >
                                    {ex.label}
                                </button>
                            ))}
                        </div>
                    </div>

                    <form onSubmit={handleSubmit}>
                        <textarea
                            id="case-input"
                            value={caseText}
                            onChange={(e) => {
                                if (e.target.value.length <= MAX_CHARS) setCaseText(e.target.value);
                            }}
                            placeholder="Describe your project, product, or startup idea in detail. Include the problem you're solving, target users, tech stack, and business model. The more detail you provide, the better the AI evaluation..."
                            rows={8}
                            style={{ width: "100%", padding: "1rem", marginBottom: "0.5rem" }}
                        />

                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "1rem" }}>
                            <span style={{
                                fontSize: "0.78rem",
                                color: remaining < 200 ? (remaining < 50 ? "var(--red)" : "var(--yellow)") : "var(--text-muted)"
                            }}>
                                {remaining.toLocaleString()} characters remaining
                            </span>
                            <span style={{ fontSize: "0.78rem", color: "var(--text-muted)" }}>
                                Min ~50 chars recommended
                            </span>
                        </div>

                        {error && (
                            <div style={{
                                padding: "0.75rem 1rem",
                                background: "rgba(239,68,68,0.1)",
                                border: "1px solid rgba(239,68,68,0.3)",
                                borderRadius: "var(--radius-md)",
                                color: "#f87171",
                                fontSize: "0.85rem",
                                marginBottom: "1rem"
                            }}>
                                ⚠️ {error}
                            </div>
                        )}

                        <button
                            id="evaluate-btn"
                            type="submit"
                            disabled={loading || caseText.trim().length < 1}
                            className="btn btn-primary btn-lg"
                            style={{ width: "100%" }}
                        >
                            {loading ? (
                                <>
                                    <div className="spinner" />
                                    Agents are evaluating...
                                </>
                            ) : (
                                <>⚖️ Evaluate with Agents</>
                            )}
                        </button>
                    </form>
                </div>

                {/* Footer note */}
                <p style={{ textAlign: "center", color: "var(--text-muted)", fontSize: "0.78rem", marginTop: "1.5rem" }} className="fade-in fade-in-delay-3">
                    Evaluation takes ~30–60 seconds • Powered by OpenRouter LLMs • Verdicts saved on Monad Testnet
                </p>
            </div>
        </div>
    );
}
